// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

app.amber.agent.data.model.Conversation
app.amber.agent.data.model.MessageNode
app.amber.ai.ui.UIMessage
app.amber.ai.ui.UIMessageChoice
app.amber.ai.ui.MessageChunk
app.amber.ai.ui.UIMessageAnnotation
app.amber.ai.ui.ToolApprovalState
app.amber.ai.core.TokenUsage