import XCTest
import CryptoKit
@testable import iosApp

final class IOSSSHPrivateKeyTests: XCTestCase {
    func testGeneratedEd25519KeyRoundTripsAndMatchesPublicKey() throws {
        let generated = try IOSSSHPrivateKey.generate()

        XCTAssertTrue(generated.privateKey.hasPrefix("-----BEGIN OPENSSH PRIVATE KEY-----"))
        XCTAssertTrue(generated.publicKey.hasPrefix("ssh-ed25519 "))
        XCTAssertEqual(generated.publicKey, try IOSSSHPrivateKey.publicKey(from: generated.privateKey))
    }

    // Disposable, unencrypted fixture generated by OpenSSH ssh-keygen with a
    // five-byte comment. Its private section is already aligned (zero padding).
    // This key is used only by the parser test and is not authorized anywhere.
    func testImportsOpenSSHKeyWithAlreadyAlignedPrivateSection() throws {
        let key = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACBxe30Iqjf7siKsgPXVUvXVW0+j69YVKSZI6UoVWApqnAAAAIjRl2yb0Zds
        mwAAAAtzc2gtZWQyNTUxOQAAACBxe30Iqjf7siKsgPXVUvXVW0+j69YVKSZI6UoVWApqnA
        AAAEApADsOn5uIRGUIayMPfxbcmW1jj/5XxKL5PTNvJuBB0HF7fQiqN/uyIqyA9dVS9dVb
        T6Pr1hUpJkjpShVYCmqcAAAABWFtYmVy
        -----END OPENSSH PRIVATE KEY-----
        """
        XCTAssertEqual(try IOSSSHPrivateKey.publicKey(from: key), "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHF7fQiqN/uyIqyA9dVS9dVbT6Pr1hUpJkjpShVYCmqc")
    }

    func testInvalidPrivateKeyIsRejected() {
        assertPrivateKeyError("not an ssh key", equals: .invalidPrivateKey)
        assertPrivateKeyError(
            "-----BEGIN OPENSSH PRIVATE KEY-----\nAA==\n-----END OPENSSH PRIVATE KEY-----",
            equals: .invalidPrivateKey
        )
    }

    func testEncryptedPrivateKeyIsRejectedBeforeParsingMaterial() {
        assertPrivateKeyError(
            "-----BEGIN ENCRYPTED PRIVATE KEY-----\nAA==\n-----END ENCRYPTED PRIVATE KEY-----",
            equals: .encryptedPrivateKey
        )
    }

    func testUnsupportedPrivateKeyIsRejected() {
        assertPrivateKeyError(
            "-----BEGIN RSA PRIVATE KEY-----\nAA==\n-----END RSA PRIVATE KEY-----",
            equals: .unsupportedPrivateKey
        )
    }

    func testPrivateKeyWithChangedMaterialFailsPublicKeyConsistencyCheck() throws {
        let generated = try IOSSSHPrivateKey.generate()
        let tampered = try tamperedSeed(in: generated.privateKey)

        assertPrivateKeyError(tampered, equals: .invalidPrivateKey)
    }

    func testP256PEMPrivateKeyImportsThroughCryptoImplementation() throws {
        let pem = P256.Signing.PrivateKey().pemRepresentation

        let publicKey = try IOSSSHPrivateKey.publicKey(from: pem)

        XCTAssertTrue(publicKey.hasPrefix("ecdsa-sha2-nistp256 "))
    }

    private func assertPrivateKeyError(
        _ value: String,
        equals expected: IOSSSHError,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        XCTAssertThrowsError(try IOSSSHPrivateKey.publicKey(from: value), file: file, line: line) { error in
            XCTAssertEqual(error as? IOSSSHError, expected, file: file, line: line)
        }
    }

    private func tamperedSeed(in privateKey: String) throws -> String {
        let lines = privateKey
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(separator: "\n")
        guard lines.count >= 3,
              lines.first.map(String.init) == "-----BEGIN OPENSSH PRIVATE KEY-----",
              lines.last.map(String.init) == "-----END OPENSSH PRIVATE KEY-----" else {
            XCTFail("Generated key did not use the expected armor")
            throw IOSSSHError.invalidPrivateKey
        }
        guard let decoded = Data(base64Encoded: lines.dropFirst().dropLast().map(String.init).joined()) else {
            throw IOSSSHError.invalidPrivateKey
        }

        var bytes = decoded
        let magic = Data("openssh-key-v1\0".utf8)
        guard bytes.starts(with: magic) else { throw IOSSSHError.invalidPrivateKey }
        var offset = magic.count
        _ = try readSSHString(from: bytes, offset: &offset)
        _ = try readSSHString(from: bytes, offset: &offset)
        _ = try readSSHString(from: bytes, offset: &offset)
        guard try readUInt32(from: bytes, offset: &offset) == 1 else {
            throw IOSSSHError.invalidPrivateKey
        }
        _ = try readSSHString(from: bytes, offset: &offset)
        let privateLength = Int(try readUInt32(from: bytes, offset: &offset))
        let privateStart = offset
        guard privateLength > 0, privateLength <= bytes.count - privateStart else {
            throw IOSSSHError.invalidPrivateKey
        }

        var innerOffset = privateStart
        _ = try readUInt32(from: bytes, offset: &innerOffset)
        _ = try readUInt32(from: bytes, offset: &innerOffset)
        _ = try readSSHString(from: bytes, offset: &innerOffset)
        _ = try readSSHString(from: bytes, offset: &innerOffset)
        let materialLength = Int(try readUInt32(from: bytes, offset: &innerOffset))
        guard materialLength == 64, innerOffset < bytes.count else {
            throw IOSSSHError.invalidPrivateKey
        }
        bytes[innerOffset] = bytes[innerOffset] ^ 0xa5

        return armor(bytes)
    }

    private func readUInt32(from data: Data, offset: inout Int) throws -> UInt32 {
        guard offset >= 0, offset <= data.count - 4 else {
            throw IOSSSHError.invalidPrivateKey
        }
        let result = (UInt32(data[offset]) << 24)
            | (UInt32(data[offset + 1]) << 16)
            | (UInt32(data[offset + 2]) << 8)
            | UInt32(data[offset + 3])
        offset += 4
        return result
    }

    private func readSSHString(from data: Data, offset: inout Int) throws -> Data {
        let length = Int(try readUInt32(from: data, offset: &offset))
        guard length <= data.count - offset else { throw IOSSSHError.invalidPrivateKey }
        let result = data.subdata(in: offset..<(offset + length))
        offset += length
        return result
    }

    private func armor(_ data: Data) -> String {
        let encoded = data.base64EncodedString()
        var lines = [String]()
        var start = encoded.startIndex
        while start < encoded.endIndex {
            let length = min(70, encoded.distance(from: start, to: encoded.endIndex))
            let end = encoded.index(start, offsetBy: length)
            lines.append(String(encoded[start..<end]))
            start = end
        }
        return (["-----BEGIN OPENSSH PRIVATE KEY-----"] + lines + ["-----END OPENSSH PRIVATE KEY-----"])
            .joined(separator: "\n")
    }
}
