package app.amber.feature.ui.components.richtext.tree

import android.app.Application
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import app.amber.agent.ui.components.richtext.nativebridge.PackedAstReader
import app.amber.core.settings.Settings
import app.amber.feature.ui.components.richtext.MarkdownParseResult
import app.amber.feature.ui.components.richtext.MarkdownTreeForParityTest
import app.amber.feature.ui.components.richtext.parseRawMarkdownForParityTest
import app.amber.feature.ui.context.LocalNavController
import app.amber.feature.ui.context.LocalSettings
import app.amber.feature.ui.context.Navigator
import app.amber.highlight.Highlighter
import app.amber.highlight.LocalHighlighter
import kotlinx.coroutines.CoroutineExceptionHandler
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.ParameterizedRobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.io.File

/**
 * TD.Rust.1a Phase 3-B — the dual-render PARITY rig. Renders the SAME markdown TWICE through the
 * SAME production renderer — once driven by the JetBrains JVM tree ([JvmMdNode]), once by the
 * packed-AST native tree ([NativeMdNode]) — and asserts the two semantics dumps match. The renderer
 * is the constant; the tree engine is the only variable. This is the final proof of whether the
 * Stage-4 tree switch is render-safe.
 *
 * ## What it proves (and how it differs from the sibling tests)
 *  - [NativeMdTreeTest] pins the native tree's *accessors* against the mapping doc.
 *  - [MarkdownRendererSnapshotTest] pins the JVM render output against a golden text dump.
 *  - THIS test compares JVM-tree render vs native-tree render of identical input. Equal dumps for a
 *    sample ⇒ the renderer is engine-agnostic for that input. Unequal dumps ⇒ a real renderer
 *    divergence the `markdownAst` flag must not ship over.
 *
 * ## Seam chosen: [MarkdownTreeForParityTest] — render a pre-built result through MarkdownBlock's
 * non-streaming dispatch
 * A Compose test rule permits exactly ONE `setContent`, so the two trees must render in the SAME
 * composition. They cannot both go through `MarkdownBlock(content)` because that entry re-derives the
 * tree from the shared parse cache (one key per content), so both calls would get the same tree.
 * Markdown.kt instead exposes [MarkdownTreeForParityTest], a thin `@VisibleForTesting` composable
 * that runs the EXACT render dispatch `MarkdownBlock` reaches on a settled (non-streaming) result —
 * the `else` arm walking `result.tree.children` via the private `MarkdownNode`, or the identical
 * `MarkdownNew(content)` HTML arm. For a settled result every streaming CompositionLocal already
 * equals its default, so this is render-equivalent to `MarkdownBlock(content)`. Both engines run this
 * ONE composable; the ONLY variable is which [MdNode] tree the result carries. We render both
 * side-by-side under distinct `testTag`s and dump each subtree separately.
 *
 * ## Input alignment: tree-vs-tree on identical RAW text
 * The golden `.pmda` blobs were generated by `dump_corpus` from the RAW `.md` text (no preprocessing
 * — see [NativeMdTreeTest] KDoc). The production funnel parses PREPROCESSED text (`preProcess()` =
 * KaTeX delimiter conversion + bare-URL linkify), but preprocessing is UPSTREAM of the parse and
 * applies EQUALLY to both engines at runtime — it does not distinguish JVM from native. So for a
 * like-for-like tree comparison both paths are fed the same RAW text:
 *  - JVM tree: [parseRawMarkdownForParityTest] runs the JetBrains parse on raw text, bypassing
 *    `preProcess` exactly as the native blob did.
 *  - Native tree: [PackedAstReader] over the golden blob + [nativeMdTreeOrNull] against raw text.
 * This is tree-vs-tree parity on identical input; production preprocessing is engine-neutral.
 *
 * ## ACCEPTED divergence — narrow, cited normalization (controller ruling)
 *  - **Image alt brackets** — the JVM `linkLabel` includes the surrounding `[ ]`; the native
 *    concatenated label does not (NativeMdTree.kt `linkLabel` KDoc + spec review). Image alt surfaces
 *    in the dump as `image=<contentDescription>`, so [normalizeImageAltBrackets] strips a single
 *    leading `[` / trailing `]` from `image=` segments on both sides before comparison. This is the
 *    ONLY normalization applied — never blanket fuzzy matching.
 *  - **`[X]` uppercase task checkbox** — native = checked, JVM = unchecked (controller-accepted GFM
 *    fix; NativeMdTree.kt `taskChecked` KDoc). The semantics dump does NOT surface checkbox state
 *    (see [dumpNormalized] "does NOT capture" list), so this divergence cannot perturb the dumps and
 *    needs no normalization.
 *
 * ## ✅ The two renderer bugs this rig discovered are now FIXED (T14.5 / td-rust-1a)
 * The rig originally surfaced two genuine bugs in the production renderer's tree walk. Both are now
 * fixed with SHAPE-AGNOSTIC renderer dispatch (Markdown.kt) — the trees stay honest to their parsers:
 *
 *  - **BUG #1 (FIXED) — native headings render EMPTY.** The Heading arm of `MarkdownNode` rendered
 *    ONLY children of type [MdNodeType.Paragraph] — the JetBrains `ATX_CONTENT → Paragraph` wrapper.
 *    The native tree has NO wrapper; its heading children are FLAT inline nodes, so the filter matched
 *    nothing. FIX: render the Paragraph wrapper child when present (JVM shape), else render the
 *    heading node itself through `Paragraph()` (native shape — `Paragraph` walks the flat inline
 *    children via `appendMarkdownNodeContent`). JVM golden output is byte-identical (one Paragraph
 *    child per heading → exactly one render either way; snapshot test stays 32/32).
 *  - **BUG #2 (FIXED) — native inline code keeps its backticks.** The generic leaf arm
 *    (`node.children.isEmpty()`) of `appendMarkdownNodeContent` PRECEDED the type-specific arms, so a
 *    childless native `InlineCode`/`MathInline` leaf hit it and was appended raw (backticks /
 *    `$formula$`) instead of dispatching by type. FIX: hoist the `InlineCode` + `MathInline` arms
 *    ABOVE the leaf arm (type-dispatch before shape-dispatch). Audit of every children-shape-gated
 *    arm: only those two inline types are childless in the native tree AND have an arm after the leaf
 *    arm; the Emphasis/Strong/Strikethrough/Link arms are inline CONTAINERS that always carry content
 *    children, so they never hit the leaf arm. JVM byte-identical (those JVM nodes carry marker-token
 *    children and never matched the leaf arm).
 *
 * ## ⚠ Residual classes UNMASKED once #1/#2 were fixed (DONE_WITH_CONCERNS — documented, skipped)
 * Fixing #1/#2 promoted 9 samples to hard parity and uncovered further divergence classes the two bugs
 * had been masking. Class [A] (heading inline-token trim-space) was a renderer-fixable quirk and is now
 * RESOLVED (deliberate behavior change + golden regen); fixing it in turn unmasked two more residuals
 * ([F] ordered-list start number, [G] task-list `[x]` marker text) on samples that had been tagged [A]
 * only — both of which are ALSO renderer-shape-dispatch bugs and are now RESOLVED too (see [F]/[G]
 * below). The remaining classes are tree-/parser-level differences NOT fixable by renderer dispatch
 * without rewriting the native parser. They stay in [KNOWN_DIVERGENT_SAMPLES], skipped and individually
 * cited. The rot guard still re-promotes any that later reach parity.
 *
 *  - **[A] Heading inline-token trim-space (FIXED — parity class A resolved).** The JVM heading path
 *    renders inline content via `Paragraph(trim=true)`; the JetBrains tree splits heading text into
 *    multiple TEXT tokens at punctuation (em-dash / `(` / `"` / `:` / `.` / `'`), and each token was
 *    `.trim()`'d in the leaf arm, dropping the interior spaces. `## GFM Tables — Simple` rendered as
 *    JVM `Tables—Simple`, native `Tables — Simple`. FIX (Markdown.kt): the leaf arm no longer trims
 *    per token; the WHOLE assembled heading content is trimmed ONCE at its outer boundaries via
 *    `AnnotatedString.trimEnds()` in `Paragraph` (gated on `trim`, which only the heading path passes).
 *    Interior token-boundary spaces survive while leading/trailing heading whitespace is still removed
 *    (`## foo ` → `foo`). The JVM goldens were intentionally REGENERATED (whitespace-only restorations
 *    inside heading lines) as part of this deliberate behavior change. Samples that diverged SOLELY on
 *    [A] now render at hard parity and have left [KNOWN_DIVERGENT_SAMPLES]: 11, 12, 17, 18, 25, 31.
 *    The MarkdownEdgeShapeRenderTest `headingPreservesInteriorSpacesAroundPunctuation` /
 *    `headingTrimsOuterWhitespaceButKeepsInterior` guards pin both halves.
 *  - **[B] Backslash-escape resolution (FIXED — parity class B resolved).** The JetBrains (JVM) tree
 *    keeps a CommonMark backslash escape (`\_` / `\!` / `\*`) LITERALLY in its Text-leaf source slice
 *    (`textIn` is a raw `substring`), so escapes rendered as `\!`; the native (pulldown) tree slices
 *    the escape away (its Text node spans only the punctuation). Per CommonMark §2.4 a `\` before any
 *    ASCII-punctuation char escapes it, so the rendered text must show just the punctuation — the JVM
 *    was the wrong side. FIX (Markdown.kt): `resolveBackslashEscapes()` is applied in BOTH leaf-text
 *    render paths — the AnnotatedString leaf arm of `appendMarkdownNodeContent` (grouped-paragraph
 *    path) AND the standalone-`Text` `MdNodeType.Text` arm of `MarkdownNode` (the per-child FlowRow
 *    path a paragraph takes when it contains an Image/MathBlock, e.g. sample 32's escapable run, whose
 *    `\( \)`/`\[ \\ \]` preprocess into inline/block math). The rule replaces `\X`→`X` only for X in
 *    the CommonMark escapable set; a `\` before a non-punctuation char (`back\slash`, `\a \z \1`) or a
 *    trailing `\` stays literal, and InlineCode/MathInline/CodeBlock slice their own raw source (their
 *    arms are hoisted ABOVE the leaf/Text arm), so code/math escapes stay raw. Applying the SAME rule
 *    to the SHARED leaf paths is idempotent on the native tree (its `!` has no backslash to strip).
 *    The JVM goldens were intentionally REGENERATED (backslash removals before escapable punctuation,
 *    samples 03 + 32 only). Sample 03 (whose ONLY divergence was the `middle\_of\_a\_word` escape) is
 *    promoted to hard parity and has left [KNOWN_DIVERGENT_SAMPLES]; sample 32's `\! \#…` escape lines
 *    now MATCH both trees — it stays skipped only on a residual [D] link/href pair the [B] divergence
 *    was masking (parity-rig first-diff 2026-06-12: 2 differing lines, both `links=`). The
 *    MarkdownEdgeShapeRenderTest `escapedPunctuationRendersLiterallyWithoutEmphasis` /
 *    `backslashBeforeNonPunctuationStaysLiteral` / `escapeInsideInlineCodeStaysRaw` guards pin the
 *    fix and its two scope boundaries.
 *  - **[B-tilde] Single-tilde strikethrough delimiter (parser-level; NOT backslash-escape, NOT fixed
 *    by the [B] escape fix).** Source `~this is not struck~`: JVM keeps the literal `~`, native strips
 *    it as a strikethrough delimiter. A parser delimiter disagreement in the renderer's INPUT (sample
 *    23), unrelated to backslash escapes; stays documented.
 *  - **[C] List-item inline-run grouping (FIXED — T14.6).** A TIGHT list item's inline content
 *    (`- Call `code` to…`) is a single grouped Text run on the JVM tree (a PARAGRAPH wrapper child)
 *    but FLAT inline children on the native tree (no Paragraph wrapper — same structural family as
 *    the old BUG #1, but in `ListItemNode`'s per-child loop). The old per-child loop rendered `Call`
 *    / `code` / `to…` as separate Text composables on the native shape. FIX (Markdown.kt): in
 *    `ListItemNode`, dispatch on shape — if the item's direct content contains a Paragraph wrapper
 *    (JVM) render per-child as before; otherwise (native flat inline) group the whole inline run
 *    through ONE `Paragraph()` via the render-time `InlineRunMdNode` view (children = the real flat
 *    inline nodes, nested lists excluded). JVM is byte-identical: the JVM branch is the unchanged
 *    original loop, and the snapshot suite (JVM-tree path) stays 32/32. Samples 10 + 13 promoted to
 *    hard parity; sample 24's [C] component is resolved too (it stays skipped only on the distinct
 *    [B-CJK] strong-emphasis class below).
 *  - **[C-para] Paragraph inline-run grouping around an Image/MathBlock (NOT fixed — different render
 *    path from [C]).** Sample 19's `Block (display) math … $$...$$ … inline math.` paragraph contains a
 *    block-level `MathBlock` child, which routes the WHOLE paragraph through the renderer's per-child
 *    FlowRow path (each direct child rendered as its own composable), NOT the grouped `Paragraph()`
 *    path that the [C] `InlineRunMdNode` fix covers. On that per-child path the JVM tree's MANY Text
 *    leaves (split at `(`/`)`/`:` punctuation — `Block`, `display`, `math uses…`, …) each become a
 *    SEPARATE dump line, while the native tree's 3 grouped leaves (`Block (display) math…signs: ` ·
 *    MathBlock · `. It renders…`) become 3 lines — shifting EVERY subsequent line (parity-rig first-diff
 *    2026-06-12: 45 differing lines, a pure top-to-bottom shift, no break nodes anywhere in the tree).
 *    This is the paragraph analog of list-item [C] but on the Image/MathBlock per-child branch, which
 *    the [C] fix deliberately did not touch; extending the grouping there is a larger change than the
 *    `ListItemNode` shape dispatch and is left for a follow-up. Sample 19 was previously mis-tagged
 *    `[C]+[E]` — corrected to `[C-para]` (it has ZERO soft breaks; the `[E]` half was fictional).
 *  - **[B-CJK] CJK-flanked strong emphasis (parser-level; unmasked when [C] was fixed in 24).**
 *    Source `常被称为**"离线优先"**策略`: the JVM (JetBrains) tree forms a Strong node (renders bold,
 *    `**` stripped); the native (pulldown-cmark) tree does NOT match the `**` delimiter run when both
 *    flanks are CJK — CommonMark's left/right-flanking rules treat CJK as non-punctuation, so the run
 *    is simultaneously left- and right-flanking and fails to open/close — and emits literal `*` Text
 *    leaves instead. Verified at the TREE level (TREEDIAG): a Strong child on JVM vs bare `*` Text on
 *    native. Like [B], this is a parser disagreement in the renderer's INPUT, not a shape bug.
 *  - **[D] Link / autolink / footnote / reference text.** Email autolink `<x>` (JVM keeps the
 *    brackets, native resolves a mailto link), reference links `[t][ref]` (JVM literal, native
 *    resolved), footnote definitions `[^id]:` (JVM keeps the marker text). Tree-structure differences.
 *  - **[E] Soft-break continuation leading whitespace (DIAGNOSED — parser-level, NOT renderer-fixable
 *    without regenerating the JVM golden; NOT a word-jam bug).** Inside a blockquote (or an indented
 *    list-item continuation), a soft- or hard-break CONTINUATION line carries a leading space on the
 *    JVM tree but NOT on the native tree. The two trees handle a line break differently in their INPUT:
 *      - JVM (JetBrains): NO break node. A break is the flat-sibling sequence `Text` · `Unknown "\n"` ·
 *        (`Unknown ">"` skipped by `isBlockquoteMarker`) · `Unknown " "` · `Text`. The `Unknown " "` is
 *        the SPACE of the `> ` continuation prefix, and it renders as a literal space — so the JVM
 *        render is `…line.\n Second…` (newline + leading space).
 *      - Native (pulldown): an explicit `SoftBreak`/`HardBreak` leaf whose span IS the literal break
 *        slice (`"\n"`, `"  \n"`, or `"\\n"`). The renderer has NO dedicated break arm, so the break
 *        leaf falls into the generic leaf arm and appends that slice verbatim — emitting the newline.
 *        The continuation `Text` leaf begins at the first NON-whitespace char (the `> ` prefix is sliced
 *        away by the parser), so the native render is `…line.\nSecond…` (newline, NO leading space).
 *    IMPORTANT — this is NOT the word-jam bug the divergence was suspected to be. The native break leaf
 *    self-carries `"\n"`, so words are NEVER glued (`line1line2`); both trees emit a newline, they
 *    differ ONLY by whether a single leading space follows it (TREEDIAG 2026-06-12, sample 27 trees +
 *    renders). The divergence direction is the OPPOSITE of the fixed native-side classes [A]/[B]/[F]/[G]:
 *    here the NATIVE side is CommonMark-correct (a blockquote/indent continuation prefix is structural
 *    and must be stripped) and the JVM side carries the COSMETIC extra space. Reaching parity would
 *    require EITHER making native add a spurious space (degrading the correct output) OR dropping the
 *    JVM leading space — which REGENERATES the JVM golden (the snapshot pins `" Second"`/`" Third"`/
 *    `" Fourth"` as production behavior, MarkdownRendererSnapshotTest 27 lines 24-26). The flag is
 *    default-OFF, so the production (JVM) golden is authoritative and must not move for a flag that
 *    isn't on. And it is NOT a renderer-shape concern: both trees walk the SAME flat-sibling leaf path,
 *    and the JVM `Unknown " "` continuation-indent token is structurally indistinguishable from a
 *    genuine inter-word space, so the renderer cannot strip it without a fragile 3-token lookbehind
 *    heuristic. Left SKIPPED + documented. Affected: 16 (the `— Jim Highsmith` blockquote line) and 27
 *    (4 lines: blockquote soft/hard-break continuations + a list-item hard-break continuation). Sample
 *    19 was PREVIOUSLY mis-tagged `[C]+[E]`; it has ZERO break nodes (TREEDIAG 2026-06-12) — its
 *    divergence is purely class [C], re-tagged below.
 *  - **[F] Ordered-list start number (FIXED — parity class F resolved).** A list `7. … 8. …` renders
 *    with the SOURCE start number on the JVM tree, which slices each item's literal LIST_NUMBER token
 *    (`7.`, `8.`, …); the native tree has NO literal marker child, so the renderer's old `?: "$index. "`
 *    fallback RENUMBERED from `1.` (`1. 2. 3.` for an authored `7. 8. 9.`). FIX (Markdown.kt
 *    `OrderedListNode`): when the literal LIST_NUMBER marker is ABSENT (native shape) derive the number
 *    from the list's `listStart` accessor — `(listStart ?: 1) + itemIndex` — which both trees decode to
 *    the first item's number (`listStart == 7L` on sample 14, both trees). JVM is byte-identical: the
 *    Unknown marker is always present on the JVM tree, so the literal slice still wins and the computed
 *    branch is native-only by construction. `start=1` / nested ordered lists have `listStart == 1` and
 *    still render `1. 2. 3.`. Sample 14 promoted to hard parity; the
 *    MarkdownEdgeShapeRenderTest `nativeOrderedListStartRendersSourceNumbers` guard pins it.
 *  - **[G] Task-list `[x]` marker text (FIXED — parity class G resolved).** Source `- [x] Increment …`:
 *    the JVM tree relocates the `[x]` into a TaskListMarker node OUTSIDE the Paragraph wrapper (rendered
 *    as a checkbox composable, marker stripped from the text run); the native tree emits the checkbox as
 *    a CHILDLESS TaskListMarker LEAF flat among the item's inline children, and the class-[C] inline-run
 *    grouping fed that leaf into Paragraph where its raw `[x]` text surfaced (`[x]Increment …`). FIX
 *    (Markdown.kt `ListItemNode`, native flat-inline branch): render any TaskListMarker child as the
 *    checkbox via `MarkdownNode` (exactly as the JVM per-child loop does) and EXCLUDE it from the
 *    grouped inline run, so the `[x]` text never reaches Paragraph on either shape. The `[X]` uppercase
 *    checkbox-STATE divergence stays accepted (invisible to the dump — see ACCEPTED divergence above);
 *    only the marker TEXT is fixed here. JVM is byte-identical: its task items carry a Paragraph wrapper
 *    and take the per-child branch, so the fixed branch is native-only for task items by construction.
 *    Sample 15 promoted to hard parity; sample 29's [G] component is resolved too (it stays skipped only
 *    on the distinct [D] footnote-definition class below). The MarkdownEdgeShapeRenderTest
 *    `nativeTaskItemRendersCheckboxAndExcludesMarkerText` guard pins it.
 *
 * The residuals that REMAIN live in the SHARED renderer's INPUT (the tree), not its shape-dispatch, so
 * the `markdownAst` flag must stay default-false until [D]/[E]/[C-para] (and the parser-level
 * [B-tilde] / [B-CJK]) are resolved. [E] (soft-break continuation leading-space) was DIAGNOSED
 * 2026-06-12 and confirmed NOT renderer-fixable as a native-side shape fix: the native side is
 * CommonMark-correct and the JVM golden carries the cosmetic leading space, so parity would require
 * regenerating the production (JVM) golden for a flag that is OFF — out of scope and explicitly not a
 * native-side fix. It is NOT a word-jam bug (native break leaves self-carry `\n`). [C-para] (paragraph
 * inline-run grouping around a MathBlock) is a real renderer concern but on the per-child FlowRow path
 * the list-item [C] fix deliberately did not cover; a follow-up. Classes [A] (heading trim-space),
 * [B] (backslash-escape resolution), [C] (list-item inline-run grouping), [F] (ordered-list start
 * number) and [G] (task-list `[x]` marker text) are now FIXED (see above) — all renderer-side,
 * shape-agnostic or shared-leaf concerns. See the T14.5 handoff parity report for the full breakdown.
 *
 * Robolectric scaffolding (config / theme / locals / async-load handler) mirrors
 * [MarkdownRendererSnapshotTest] verbatim — a parity gap is attributable to the tree, not the harness.
 */
@RunWith(ParameterizedRobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [34], application = Application::class)
class MarkdownTreeParityTest(
    private val sampleName: String,
    private val sampleFile: File,
) {

    // Same async-load swallow as the snapshot test: the QuickJS/Prism highlighter loads a native
    // `.so` absent on the host JVM, so HighlightText's off-thread highlight() resumes with an
    // UnsatisfiedLinkError (possibly wrapped). The dumped code Text is the raw source either way, so
    // we swallow it in the compose effect context rather than crash waitForIdle().
    private val swallowAsyncLoadFailures = CoroutineExceptionHandler { _, t ->
        if (generateSequence<Throwable>(t) { it.cause }.none { it is UnsatisfiedLinkError }) {
            throw t
        }
    }

    @get:Rule
    val compose = createComposeRule(swallowAsyncLoadFailures)

    @Test
    fun nativeTreeRendersEquivalentlyToJvmTree() {
        val rawText = sampleFile.readText()
        val blob = blobFileFor(sampleName).readBytes()

        // ── JVM tree over RAW text (JetBrains parse, preProcess bypassed) ──
        val jvmResult = parseRawMarkdownForParityTest(rawText)

        // ── Native tree over the SAME RAW text, from the golden blob (no JNI on host) ──
        val reader = PackedAstReader(blob)
        assertTrue("$sampleName: golden blob invalid — regen corpus", reader.isValid && reader.validate())
        val nativeRoot = nativeMdTreeOrNull(reader, rawText)
            ?: throw AssertionError("$sampleName: native tree had no decodable root")
        val nativeResult = MarkdownParseResult(
            preprocessed = rawText,
            tree = nativeRoot,
            hasHtmlBlocks = reader.hasHtmlBlocks,
        )

        // hasHtmlBlocks MUST agree: if it didn't, one engine would route to MarkdownNew (HTML
        // re-parse) and the other to the tree path — a structural divergence, not a render nit.
        // The blob-header bit and JVM containsHtmlBlocks() are designed to match (Markdown.kt
        // parsePreprocessedMarkdownUncached KDoc). Assert it so a regression surfaces loudly.
        assertEquals(
            "$sampleName: hasHtmlBlocks disagree (JVM=${jvmResult.hasHtmlBlocks} " +
                "native=${nativeResult.hasHtmlBlocks}) — would split the render path",
            jvmResult.hasHtmlBlocks,
            nativeResult.hasHtmlBlocks,
        )

        // Render BOTH engines in one composition (a Compose test rule allows only one setContent),
        // each under a distinct testTag so we can dump the two subtrees independently.
        val highlighter = Highlighter(RuntimeEnvironment.getApplication())
        compose.setContent {
            CompositionLocalProvider(
                LocalSettings provides Settings(),
                LocalNavController provides Navigator(mutableListOf()),
                LocalHighlighter provides highlighter,
            ) {
                MaterialTheme {
                    Column {
                        Box(Modifier.testTag(TAG_JVM)) {
                            MarkdownTreeForParityTest(content = rawText, result = jvmResult)
                        }
                        Box(Modifier.testTag(TAG_NATIVE)) {
                            MarkdownTreeForParityTest(content = rawText, result = nativeResult)
                        }
                    }
                }
            }
        }
        compose.waitForIdle()

        // dumpNormalized ignores the TestTag property (it captures only Text/ContentDescription/
        // Role/Image/links), so the tagged Box contributes no dump line — only its rendered subtree.
        val jvmDump = compose.onNodeWithTag(TAG_JVM).fetchSemanticsNode().dumpNormalized()
        val nativeDump = compose.onNodeWithTag(TAG_NATIVE).fetchSemanticsNode().dumpNormalized()

        val jvmNorm = jvmDump.normalizeImageAlt()
        val nativeNorm = nativeDump.normalizeImageAlt()
        val parity = jvmNorm == nativeNorm

        if (sampleName in KNOWN_DIVERGENT_SAMPLES) {
            // Rot guard: a known-divergent sample that now MATCHES means a renderer fix landed —
            // promote it back to a hard-parity sample so the proof tightens.
            if (parity) {
                throw AssertionError(
                    "$sampleName now renders at parity — remove it from KNOWN_DIVERGENT_SAMPLES " +
                        "(its documented residual divergence class [D]/[E]/[C-para] / [B-tilde] / " +
                        "[B-CJK] appears fixed).",
                )
            }
            // Still divergent as documented — skip loudly (visible as SKIPPED, never a false PASS).
            assumeTrue(
                "$sampleName diverges due to a documented residual tree-/parser-level class " +
                    "([D] link-footnote text / [E] soft-break continuation leading-space / [C-para] " +
                    "paragraph inline-run grouping around a MathBlock / [B-tilde] single-tilde strike / " +
                    "[B-CJK] CJK-flanked strong — see class KDoc + parity report). BUG #1 " +
                    "(heading-drop), BUG #2 (inline-code-backtick), class [A] (heading trim-space), " +
                    "class [B] (backslash-escape resolution), class [C] (list-item inline-run grouping), " +
                    "class [F] (ordered-list start number) and class [G] (task-list `[x]` marker text) " +
                    "are FIXED; these residuals must be resolved before markdownAst can flip on.",
                false,
            )
        }

        // Non-divergent sample: assert HARD parity.
        if (!parity) {
            throw AssertionError(buildParityDiff(sampleName, jvmNorm, nativeNorm))
        }
    }

    private fun String.normalizeImageAlt(): String =
        lines().joinToString("\n") { it.normalizeImageAltBrackets() }

    companion object {
        private val CORPUS_DIR = File(MARKDOWN_CORPUS_DIR)
        private const val TAG_JVM = "parity-jvm-tree"
        private const val TAG_NATIVE = "parity-native-tree"

        /**
         * Samples whose JVM-tree and native-tree renders STILL diverge after BUG #1 (heading-drop),
         * BUG #2 (inline-code-backtick), class [A] (heading inline-token trim-space) and class [B]
         * (backslash-escape resolution) were fixed. Each remaining sample is tagged with the residual
         * class [D]…[G] (or the parser-level [B-tilde] / [B-CJK]) documented in the class KDoc — these
         * are tree-/parser-level differences, NOT the renderer-shape-dispatch bugs T14.5 addressed, the
         * trim-space quirk [A], or the Text-leaf escape resolution [B]. They are SKIPPED (not failed,
         * not passed) so the suite is green WITHOUT pretending the native tree renders correctly — and
         * the rot guard re-promotes any that later reach parity. Samples that are NOW (or were always)
         * at hard parity are NOT here:
         *  - 01, 02, 07, 08, 09, 21, 26 — promoted to hard parity by the BUG #1/#2 fixes.
         *  - 11, 12, 17, 18, 25, 31 — promoted to hard parity by the class [A] heading trim-space fix.
         *  - 03 — promoted to hard parity by the class [B] backslash-escape fix (its only divergence
         *    was the `middle\_of\_a\_word` escape; both trees now render `middle_of_a_word`).
         *  - `20-html-block` — `hasHtmlBlocks`, both engines route to the identical `MarkdownNew`
         *    HTML path, so the tree is bypassed (trivially equal, but a real datapoint: the HTML
         *    arm is parity-safe).
         *  - `30-empty-and-whitespace` — whitespace-only input, both render nothing.
         */
        private val KNOWN_DIVERGENT_SAMPLES: Set<String> = setOf(
            // BUG #1 (native-heading-drop), BUG #2 (native-inline-code-backtick), class [A]
            // (heading inline-token trim-space), class [B] (backslash-escape resolution), class [C]
            // (list-item inline-run grouping), class [F] (ordered-list start number) and class [G]
            // (task-list `[x]` marker text) are ALL FIXED with shape-agnostic renderer dispatch in
            // Markdown.kt. Samples that diverged SOLELY on those have left this list:
            //   01, 02, 07, 08, 09, 21, 26 (BUG #1/#2),  11, 12, 17, 18, 25, 31 (class [A]),
            //   03-emphasis-nesting (class [B] — `middle\_of\_a\_word`),  10, 13 (class [C]),
            //   14-ordered-list-start (class [F]),  15-task-lists (class [G]).
            // 20-html-block / 30-empty were never listed.
            // The samples that REMAIN here diverge on the residual tree-/parser-level classes those
            // fixes UNMASKED (see class KDoc §"residual classes"). These are NOT renderer-shape-dispatch
            // bugs fixable without rewriting the native parser, so they stay skipped and cited. Tag
            // legend: [B] backslash-escape resolution, [C] list-item inline-run grouping (FIXED),
            // [C-para] paragraph inline-run grouping around a MathBlock (per-child path; NOT fixed),
            // [D] link/autolink/footnote/reference text, [E] soft-break continuation leading-space
            // (parser-level; native correct, JVM keeps a cosmetic leading space; NOT a word-jam),
            // [F] ordered-list start number, [G] task-list `[x]` marker text.
            "04-links-inline",            // [D] email autolink `<x>` kept by JVM, resolved by native
            "05-links-with-titles",       // [D] reference link `[t][ref]` literal (JVM) vs resolved
            "06-images",                  // [D] inline-image run split differs between trees
            // 10-inline-code, 13-nested-lists: class [C] (list-item inline-run grouping) RESOLVED by
            // the shape-agnostic ListItemNode dispatch (Markdown.kt InlineRunMdNode) — both now render
            // at hard parity and have left this list.
            // class [A] (heading inline-token trim-space) is RESOLVED — the heading render path now
            // trims the assembled heading content ONCE at its outer boundaries instead of trimming
            // each leaf token (Markdown.kt: leaf arm no longer trims; AnnotatedString.trimEnds() in
            // Paragraph). 6 samples that diverged SOLELY on [A] now render at hard parity and have
            // left this list: 11, 12, 17, 18, 25, 31. The 6 samples below were ALSO tagged [A] but
            // diverge on a SECOND class that [A] was masking; their heading lines now match, so they
            // are re-tagged with the residual class proven at the tree-dump level (parity-rig first-diff
            // captured 2026-06-12):
            // 14-ordered-list-start, 15-task-lists: classes [F] (ordered-list start number) and [G]
            // (task-list `[x]` marker text) are RESOLVED by the shape-agnostic OrderedListNode +
            // ListItemNode dispatch (Markdown.kt) — both now render at hard parity and have left this
            // list.
            "16-blockquotes-nested",      // [E]+[D-bq] 2 lines (parity first-diff 2026-06-12): (1) [E]
                                          //     blockquote soft-break continuation `— Jim Highsmith`
                                          //     carries a leading space on JVM, none on native; (2)
                                          //     [D-bq] a code block INSIDE a blockquote — JVM keeps the
                                          //     `> ` continuation prefix in the fence body (`> val msg…`),
                                          //     native slices it (`val msg…`). Both parser-level.
            "19-katex-block",             // [C-para] paragraph inline-run grouping around a MathBlock
                                          //     (NOT [E] — zero break nodes): the MathBlock-containing
                                          //     paragraph takes the per-child FlowRow path; JVM's many
                                          //     punctuation-split Text leaves render as separate lines,
                                          //     native's 3 grouped leaves as 3 — a 45-line top-to-bottom
                                          //     shift. Different render path from the fixed list-item [C].
            "22-footnotes",               // [D] footnote def `[^id]:` text kept (JVM) vs stripped
            "23-strikethrough",           // [B-tilde] single tilde `~this is not struck~`: JVM keeps
                                          //     literal `~`, native strips it (parser delimiter
                                          //     disagreement — NOT backslash-escape; the [B] escape fix
                                          //     does not touch it)
            // 24-cjk-mixed: the [C] list-item inline-run split is now RESOLVED (its list items render
            // at parity via the shape-agnostic dispatch). A DISTINCT residual remains and keeps it
            // here: [B-CJK] CJK-flanked strong emphasis. Source `常被称为**"离线优先"**策略` — the JVM
            // (JetBrains) tree forms a Strong node (renders bold, markers stripped); the native
            // (pulldown-cmark) tree does NOT match the `**` delimiter run when both flanks are CJK
            // (CommonMark left/right-flanking rules treat CJK as non-punctuation, so the run is both
            // left- and right-flanking and fails to open/close), emitting literal `*` Text leaves.
            // Verified at the TREE level (parity-test TREEDIAG): JVM paragraph has a Strong child,
            // native paragraph has bare `*`/`*` Text children — a parser-level divergence in the
            // renderer's INPUT, NOT a renderer-shape bug. Same family as [B] backslash-escape (the two
            // parsers resolve the same source differently), not [C].
            "24-cjk-mixed",               // [B-CJK] `**"离线优先"**` strong (JVM) vs literal `**` (native)
            "27-hard-soft-breaks",        // [E] 4 lines (parity first-diff 2026-06-12), ALL the
                                          //     continuation leading-space pattern: 3 blockquote soft/
                                          //     hard-break continuations (`Second`/`Third`/`Fourth`) +
                                          //     1 list-item hard-break continuation (`First item, second
                                          //     line`). JVM keeps a leading space, native (correct) does
                                          //     not. Native NEVER jams words — its break leaf carries
                                          //     `\n`; both emit a newline (see class [E] KDoc).
            "28-link-edge-cases",         // [D] link/href: escaped-paren URL `path\(1\)` is preprocessed
                                          //     into the link DESTINATION (href), never a Text leaf, so
                                          //     the class-[B] Text-leaf escape fix does not reach it —
                                          //     the residual is purely a link/href parser divergence.
            "29-mixed-everything",        // [D] footnote def text ONLY (class [G] task markers RESOLVED):
                                          //     the `[x]` task items (lines 13-17) now render at parity
                                          //     via the shape-agnostic checkbox dispatch. The residual is
                                          //     the footnote DEFINITIONS `[^agpl]:` / `[^commercial]:` —
                                          //     JVM keeps the literal marker text, native strips it and
                                          //     resolves the URL as a link (parity-rig first-diff
                                          //     2026-06-12: only the 2 footnote-def lines differ).
            "32-special-chars-escapes",   // [D] residual link/href ONLY (class [B] escapes RESOLVED):
                                          //     escaped-bracket `\[not a link\](url)` — JVM attaches a
                                          //     `links=` annotation, native renders bare text; and an
                                          //     HTML-entity-in-URL href (`&amp;url` JVM vs `&url` native).
                                          //     All `\! \#…` escape lines now MATCH (parity-rig first-diff
                                          //     2026-06-12: only the 2 link lines differ).
        )

        private fun blobFileFor(sampleName: String): File = File(CORPUS_DIR, "$sampleName.pmda")

        @JvmStatic
        @ParameterizedRobolectricTestRunner.Parameters(name = "{0}")
        fun samples(): List<Array<Any>> =
            CORPUS_DIR.listFiles { f -> f.extension == "md" }
                .orEmpty()
                // Only samples that have a paired golden blob can be compared tree-vs-tree.
                .filter { File(CORPUS_DIR, "${it.nameWithoutExtension}.pmda").exists() }
                .sortedBy { it.name }
                .map { arrayOf(it.nameWithoutExtension, it) }

        /**
         * ACCEPTED divergence #1 (image alt brackets). The dump renders image alt text as
         * `image=<contentDescription>`. The JVM tree's image alt is the RAW LINK_TEXT including the
         * surrounding `[ ]` (NativeMdTree.kt `linkLabel` KDoc: "the image-alt call site uses the
         * label as-is … native alt text lacks the brackets the JVM alt carries"). The bracket
         * presence is non-visible accessibility metadata, so we strip ONE leading `[` and ONE
         * trailing `]` from the alt segment of `image=` lines on both sides before comparison.
         */
        private fun String.normalizeImageAltBrackets(): String {
            val marker = "image="
            val idx = indexOf(marker)
            if (idx < 0) return this
            val prefix = substring(0, idx + marker.length)
            var alt = substring(idx + marker.length)
            if (alt.startsWith("[")) alt = alt.substring(1)
            if (alt.endsWith("]")) alt = alt.substring(0, alt.length - 1)
            return prefix + alt
        }

        /** Unified-ish diff between the two engines plus the first differing line. */
        private fun buildParityDiff(name: String, jvm: String, native: String): String {
            val j = jvm.lines()
            val n = native.lines()
            val firstDiff = (0 until maxOf(j.size, n.size)).firstOrNull {
                j.getOrNull(it) != n.getOrNull(it)
            }
            val pointer = if (firstDiff != null) {
                "\nfirst diff at line ${firstDiff + 1}:\n" +
                    "  jvm:    ${j.getOrNull(firstDiff)}\n" +
                    "  native: ${n.getOrNull(firstDiff)}"
            } else {
                ""
            }
            return buildString {
                appendLine("dual-tree render parity mismatch for sample '$name'")
                appendLine("(JVM JetBrains tree vs native packed-AST tree, same renderer, same raw input)")
                appendLine("If this is one of the two DOCUMENTED renderer bugs (native heading-drop /")
                appendLine("native inline-code-backtick), add '$name' to KNOWN_DIVERGENT_SAMPLES with a")
                appendLine("citation. If it is a NEW divergence, investigate the root cause first.")
                appendLine(pointer)
                appendLine("----- JVM TREE DUMP -----")
                appendLine(jvm)
                appendLine("----- NATIVE TREE DUMP -----")
                appendLine(native)
            }
        }
    }
}
